### ISSUE TITLE
Refactor breaks intergration

### ISSUE THREAD

**Issue by tetsuo55** [lymanepp/thermal_comfort#7]
Logger: homeassistant.components.sensor
Source: custom_components/thermal_comfort/sensor.py:81
Integration: Sensor (documentation, issues)
First occurred: 22:23:44 (1 occurrences)
Last logged: 22:23:44

Error while setting up thermal_comfort platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/thermal_comfort/sensor.py", line 81, in async_setup_platform
    if sensor_type in SENSOR_TYPES:
TypeError: unhashable type: 'dict_keys'

**Comment by lymanepp** [comment]
I'm done refactoring now. Sorry you caught me in the middle.
